Review
rebel1866/Nikea pull request #3
Opened 2023-11-19 13:09 UTC by rebel1866

2023-11-21 14:11 UTC, vovan- commented on README.md
This is a good place to describe all the details on what is a project about, how it works, how to build, setup and test it locally

2023-11-21 14:58 UTC, vovan- commented on api-gateway/src/main/java/com/nikea/config/GatewayConfig.java
> +                .route("productId", r->r.path("/product/**").uri("lb://PRODUCT-SERVICE"))
In such configuration way if we want to change any route path or service name  we will have to recompile and redeploy entire api-gateway application.
Let's investigate how to do this via configuration, and maybe even via cloud config

2023-11-21 15:05 UTC, vovan- commented on config-server/src/main/resources/application.properties
> +spring.security.user.name=admin
As agreed, we do not want to store secrets in the repository, instead we should provide an option to configure it at runtime, e.g via environment variables and we can document in the readme file how to do so.

2023-11-21 15:08 UTC, vovan- commented on monitoring/docker-compose.yml
> +    image: prom/prometheus:v2.44.0
The current stable version at the time of this implementation is https://hub.docker.com/layers/prom/prometheus/v2.48.0/images/sha256-13f40c0279df792517b456ae6427dd6344685e9b1478fb9de8e4dc418727668f?context=explore 
It makes sense to review the versions, as updates might include important security patches as well as bug fixes

2023-11-21 18:12 UTC, vovan- commented on monitoring/docker-compose.yml
> +    image: grafana/grafana:9.5.2
The same here https://hub.docker.com/layers/grafana/grafana/9.5.14/images/sha256-a0ab21d92c3bc978b3ef55972f12482455abeacd7dd1e295ce480a90cca44c80?context=explore

2023-11-21 18:13 UTC, vovan- commented on monitoring/prometheus/prometheus.yml
> +      - targets: ['192.168.100.62:9008']
Is this a docker ip or somethings else? If it is can this be configured via dns name to be reusable on other machines?

2023-11-21 18:14 UTC, vovan- commented on order-service/pom.xml
> +		<java.version>17</java.version>
Btw just curious why you decided not to try java 21;)

2023-11-21 18:16 UTC, vovan- commented on order-service/src/main/java/com/nikea/productservice/dao/model/Order.java
> +    private Integer totalPrice;
is the price decimal or not?

2023-11-22 10:13 UTC, vovan- commented on order-service/src/main/java/com/nikea/productservice/service/exception/OrderServiceException.java
> +    public OrderServiceException(String message) {
Usually we might want to include original throwable param as well to have a root cause stack analysis

2023-11-22 10:14 UTC, vovan- commented on order-service/src/main/java/com/nikea/productservice/service/logic/impl/OrderServiceImpl.java
> +    private @Autowired ProductService productService;
As I've commented on the wiki page let's also introduce some distributed write transaction by updating both order and product

2023-11-22 10:15 UTC, vovan- commented on order-service/src/main/java/com/nikea/productservice/service/logic/impl/OrderServiceImpl.java
> +    private @Autowired OrderRepository orderRepository;
btw, as we use lombok, why don't we have required args constructor annotation and just constructor injection without all these @Autowired annotations?

2023-11-22 10:19 UTC, vovan- commented on order-service/src/main/java/com/nikea/productservice/service/logic/pricestrategy/PriceStrategyHolder.java
> +public class PriceStrategyHolder {
Nice switch alternative!
Event better it would be if you replace static list of classes with autowired list which will be populated by spring context

2023-11-22 10:29 UTC, vovan- commented on product-service/src/main/java/com/nikea/productservice/service/logic/impl/ProductServiceImpl.java
> +            lockAcquired = lock.tryLock(2, TimeUnit.SECONDS);
lock acquisition should be part of the second try case, as there is finally block that will release this lock in case of any exception, with the current approach if we have any coding error, we will have a lock stuck

2023-11-22 10:38 UTC, vovan- commented on pom.xml
> +        <spring-cloud.version>2022.0.1</spring-cloud.version>
At the time of implementation this is not the latest up to date version, here is a fresh one:
https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies/2022.0.4
even this one contains vulnerabilities already, but fewer compared to the current one used:
Vulnerabilities from dependencies:
CVE-2023-4759
CVE-2023-20859

2023-11-22 10:40 UTC, vovan- commented on order-service/src/main/resources/bootstrap.properties
> +spring.application.name=ORDER-SERVICE
A couple of questions here:
- do we still need boostrap file? Since some of the spring boot versions it is not used anymore, there is no boostrap context, so I am wondering if spring cloud still relies on that?
- if it is still needed, then the question is do we still need to duplicate same values in application.yaml?

2023-11-22 10:42 UTC, vovan- commented on service-discovery/pom.xml
> +        <spring-cloud.version>2022.0.3</spring-cloud.version>
can we share configuration for the dependencies defined in one root place and not to duplicate them across maven sub modules, it helps in such kind of setups a lot, you just need to change it once e.g. when you need to make an updated

2023-11-22 10:42 UTC, vovan- commented on service-discovery/pom.xml
> +        <spring-cloud.version>2022.0.3</spring-cloud.version>
Also it looks like we have various versions used by various sub modules

2023-11-22 10:43 UTC, vovan- requested changes
Please have a look at the comments

2023-11-22 16:10 UTC, rebel1866 commented on api-gateway/src/main/java/com/nikea/config/GatewayConfig.java
> +                .route("productId", r->r.path("/product/**").uri("lb://PRODUCT-SERVICE"))
Gateway java configuration has been replaced by configuration defined in application.yml - as a result there is no need to recompile an redeploy application when it's necessary to change some routes/ predicates etc.

2023-11-22 17:00 UTC, rebel1866 commented on README.md
README.md is added with brief description 1f1cdcfe60b51b798c88bf3f270fd47ff2f837b4

2023-11-22 17:46 UTC, rebel1866 commented on order-service/src/main/java/com/nikea/productservice/service/logic/pricestrategy/PriceStrategyHolder.java
> +public class PriceStrategyHolder {
af00c54a6fa58d9e0823f1beed78b86e444376c5
Injected List<PriceStrategy> instead of PriceStrategyHolder

2023-11-23 10:01 UTC, rebel1866 commented on config-server/src/main/resources/application.properties
> +spring.security.user.name=admin
Resolved - secrets are now transmitted through VM options at runtime, except for cases where secrets storing is intended to demonstrate config server ciphering/deciphering abilities. 8ef2bdb9fdf2dbb57b5a68ee369a47a7880a8b9c

2023-11-23 10:03 UTC, rebel1866 commented on order-service/src/main/resources/bootstrap.properties
> +spring.application.name=ORDER-SERVICE
Seems like we don't need it anymore indeed. All bootstrap files have been removed from project 8ef2bdb9fdf2dbb57b5a68ee369a47a7880a8b9c

2023-11-23 10:15 UTC, rebel1866 commented on monitoring/docker-compose.yml
> +    image: prom/prometheus:v2.44.0
resolved 37421ae7e216623aae0b22e78ad22211ddc0ef7c

2023-11-23 10:15 UTC, rebel1866 commented on monitoring/docker-compose.yml
> +    image: grafana/grafana:9.5.2
resolved 37421ae7e216623aae0b22e78ad22211ddc0ef7c

2023-11-23 12:15 UTC, rebel1866 commented on order-service/src/main/java/com/nikea/productservice/service/logic/impl/OrderServiceImpl.java
> +    private @Autowired OrderRepository orderRepository;
resolved a50d423ed6d3134fe64256ccabb83837379556e6

2023-11-23 12:28 UTC, rebel1866 commented on product-service/src/main/java/com/nikea/productservice/service/logic/impl/ProductServiceImpl.java
> +            lockAcquired = lock.tryLock(2, TimeUnit.SECONDS);
resolved efedd1d963b58efd1c897d52c76a0e3fd64557bf

2023-11-23 12:36 UTC, rebel1866 commented on order-service/src/main/java/com/nikea/productservice/service/exception/OrderServiceException.java
> +    public OrderServiceException(String message) {
resolved 5f0b66f51f2bfee5bb98701a5a0dd8c810844ff1

2023-11-23 12:45 UTC, rebel1866 commented on order-service/pom.xml
> +		<java.version>17</java.version>
I just didn't think about it)  I get used to java 17 and it's pretty comfortable for me to work with it.

2023-11-23 13:31 UTC, rebel1866 commented on order-service/src/main/java/com/nikea/productservice/dao/model/Order.java
> +    private Integer totalPrice;
Price is decimal, fixed in 057141de494a3f405e5db590c92663ade0fb57a6

2023-11-23 13:40 UTC, rebel1866 commented on order-service/src/main/java/com/nikea/productservice/service/logic/impl/OrderServiceImpl.java
> +    private @Autowired OrderRepository orderRepository;
This is standard way we use this annotation (@Autowired) on our project. I wrote it so many times that I didn't even ask myself whether it possible to rewrite it in a more short way:) But indeed using lombok RequireAllArgsConstructor or AllArgsConstructor is much more convenient. Resolved in 1f1d65ca9ce7cb9cf7f67b19bcf42658fc35d804

2023-11-23 15:04 UTC, rebel1866 commented on pom.xml
> +        <spring-cloud.version>2022.0.1</spring-cloud.version>
resolved 81a1aa1f208d9c4761cc742655f945e40230d542

2023-11-23 15:04 UTC, rebel1866 commented on service-discovery/pom.xml
> +        <spring-cloud.version>2022.0.3</spring-cloud.version>
resolved 81a1aa1f208d9c4761cc742655f945e40230d542

2023-11-24 08:09 UTC, vovan- commented on order-service/src/main/java/com/nikea/productservice/dao/model/Order.java
> +    private Integer totalPrice;
Ok great, for the future, prices are usually handled with BigDecimail as Double and Float has limitations in calculations by design

2023-12-17 15:07 UTC, rebel1866 commented on order-service/src/main/java/com/nikea/productservice/service/logic/impl/OrderServiceImpl.java
> +    private @Autowired ProductService productService;
SAGA pattern is implemented 442e7e34e0459360c1b2527e4b6412eddbde53db

2023-12-17 16:07 UTC, rebel1866 commented on monitoring/prometheus/prometheus.yml
> +      - targets: ['192.168.100.62:9008']
that's my ip address, changed to localhost d48bd61b1ff9ac412a615aac3fc2c16456b71806

2023-12-22 07:00 UTC, vovan- commented on order-service/src/main/java/com/nikea/orderservice/service/logic/impl/OrderServiceImpl.java
> +        messageProducer.sendOrderCreationEvent(new OrderCreationEvent(order.getId(), orderDto.getFurnitureId()));
Let's imagine the following situation:
1) orderRepository.save(orderMapper.toEntity(orderDto)); is executed successfully
2) jvm crashes right after that before messageProducer.sendOrderCreationEvent is executed
In such a case event will never be sent even after the application restart.
To solve such issues ususually transactional outbox pattern is used where such messages/events are first transactionally stored to the database. And then some worker periodically fetches and publishes them to kafka.

2023-12-22 07:17 UTC, vovan- commented on order-service/src/main/java/com/nikea/productservice/service/logic/impl/OrderServiceImpl.java
> +    private @Autowired ProductService productService;
And it looks good to me! Left just one additional point

2023-12-22 07:19 UTC, vovan- commented on product-service/src/main/resources/application.properties
> +spring.kafka.bootstrap-servers=localhost:9092
With kafka there is usually a need during development to see the following:
- messages coming to the topic
- consumers connected to the topic
- message lag(unprocessed messages) in topic
Sometimes it is needed to reset topic offset if some message has wrong structure and stuck.

Which tool have you adopted to achieve the goals above?

2024-01-04 15:19 UTC, rebel1866 commented on order-service/src/main/java/com/nikea/orderservice/service/logic/impl/OrderServiceImpl.java
> +        messageProducer.sendOrderCreationEvent(new OrderCreationEvent(order.getId(), orderDto.getFurnitureId()));
Added transactional outbox pattern 30791ef7cd37c73db3bf73ac67b3f3d6084f5457

2024-01-04 16:25 UTC, rebel1866 commented on product-service/src/main/resources/application.properties
> +spring.kafka.bootstrap-servers=localhost:9092
I used Kafdrop - open source tool (web UI) for kafka monitoring.

2024-01-05 15:12 UTC, vovan- commented on order-service/src/main/java/com/nikea/orderservice/service/logic/impl/OutboxServiceImpl.java
> +            messageProducer.sendOrderCreationEvent(outbox.getMessage());
One point here: We do not ensure here that event is actually sent before deletion, usually producer returns Future which means message will be processed asyncrhonously, so having e.g. future.get() should solve the problem.

2024-01-05 15:14 UTC, vovan- commented on product-service/src/main/resources/application.properties
> +spring.kafka.bootstrap-servers=localhost:9092
I quickly reviewed this tool capability, could you please clarify how would you change offset for some topic/partition with this tool, as I cannot find this capability. 
But this is definetely precent in kafka console utilities + some other tools, e.g. kafka-ui. So having those at hand and knowing how to work with them is a benefit.

2024-01-05 15:14 UTC, vovan- approved these changes

2024-01-05 20:10 UTC, rebel1866 commented on order-service/src/main/java/com/nikea/orderservice/service/logic/impl/OutboxServiceImpl.java
> +            messageProducer.sendOrderCreationEvent(outbox.getMessage());
resolved 40201f0bab33511a5331b000b1696f2371bdce62

2024-01-05 20:14 UTC, rebel1866 commented on product-service/src/main/resources/application.properties
> +spring.kafka.bootstrap-servers=localhost:9092
I thing it would be useful for me trying other tools, for example kafka UI as per your recommendation, because Kafrop really got limited functionality.

2024-05-18 12:51 UTC, closed without merging